```{r}
# importing packages needed
library(tidyverse)
library(rvest)
library(dplyr)
library(httr2)
library(tidyr)
library(janitor)
```



```{r}
#Web scraping 
#getting top 50 most subscribed YouTube channels from Wikipedia
#Actually it turns out to be 49 because one channel (Shemaroo) was shown up twice in the Widipedia chart
read_html("https://en.wikipedia.org/wiki/List_of_most-subscribed_YouTube_channels") |>
  html_elements("td:nth-child(2)") |>
  html_text2() -> most_sub

tibble(most_sub) -> most_subs

slice(.data = most_subs, 1:50) -> most_subss

atomic_vector <- most_subss$most_sub   #making the list into atomic vector
print(atomic_vector) -> a_vector

```



```{r}
#importing data with youtube api 
#function that grabs channel ID using the channel names
base_url <- "https://www.googleapis.com/youtube/v3/search"
channlid <- function(x) {
  request(base_url) |>
    req_url_query(key = "AIzaSyB1lLY4WEyper_eQgGceS2ieGtJi3tYLSg",
                  part = "snippet",
                  q = x) |>
    req_perform() |>
    resp_body_json() -> x
    assign("x", x[["items"]][[1]][["snippet"]][["channelId"]], envir = .GlobalEnv)
}
```



```{r}
#using channelid function to grab the atomic vector of channel IDs
my_list <- list()
for (x in a_vector) {
  channlid(x) -> y
  my_list[x] <- y
} 

my_data_frame <- as.data.frame(my_list)

my_data_frame |>
  pivot_longer(cols = 1:49,
               names_to = "a",
               values_to = "channel") |>
  select(channel) -> channels
  

id_vector <- channels$channel
id_vector
```



```{r}
#importing data with YouTube api
#function that grabs channel information (statistics) 
base_url <- "https://www.googleapis.com/youtube/v3/channels"

info <- function(x) {
  request(base_url) |>
    req_url_query(key = "AIzaSyB1lLY4WEyper_eQgGceS2ieGtJi3tYLSg",
                  part = "statistics,snippet",
                  id = x) |>
    req_perform() |>
    resp_body_json() -> x
}
```



```{r}
#using info function to get statistics of 50 Youtube channels
map(.x = id_vector, .f = info) -> info_list
```



