---
title: "Data Import Script"
format: html
---

```{r packages}
library(tidyverse)
library(rvest)
library(dplyr)
library(httr2)
```



```{r}
#web scraping - finding top 50 youtuber
read_html("https://en.wikipedia.org/wiki/List_of_most-subscribed_YouTube_channels") |>
  html_elements("td:nth-child(2)") |>
  html_text2() -> most_sub

tibble(most_sub) -> most_subs

slice(.data = most_subs, 1:5) -> most_subss

atomic_vector <- most_subss$most_sub
print(atomic_vector) -> a_vector

```



```{r}
#function to get channel ID
base_url <- "https://www.googleapis.com/youtube/v3/search"
channlid <- function(x) {
  request(base_url) |>
    req_url_query(key = "AIzaSyCq_fI_CnAymFiyFHafXUBGSIVOzwXLGqc",
                  part = "snippet",
                  q = x) |>
    req_perform() |>
    resp_body_json() -> x
    assign("x", x[["items"]][[1]][["snippet"]][["channelId"]], envir = .GlobalEnv)
}
```



```{r}
#using the function to find channel ID
my_list <- list()
for (x in a_vector) {
  channlid(x) -> y
  my_list[x] <- y
} 

my_data_frame <- as.data.frame(my_list)

my_data_frame |>
  pivot_longer(cols = 1:5,
               names_to = "a",
               values_to = "channel") |>
  select(channel) -> channels
  

vector <- channels$channel
channel_id_list <- as.data.frame(vector)
```



```{r}
#example of finding statistics by using the channel ID
base_url <- "https://www.googleapis.com/youtube/v3/channels"

request(base_url) |>
  req_url_query(key = "AIzaSyA4Wsi18Ia6cYUZeX3NPxXhx3A3-lqXTBI",
                part = "snippet,contentDetails,statistics",
                id = "UCX6OQ3DkcsbYNE6H8uQQuVA") |>
  req_perform() -> respons

respons |>
  resp_body_json() -> ex2
```



```{r}
#function that extracts view count
base_url <- "https://www.googleapis.com/youtube/v3/channels"

view_count <- function(x) {
  request(base_url) |>
    req_url_query(key = "AIzaSyCq_fI_CnAymFiyFHafXUBGSIVOzwXLGqc",
                  part = "snippet,contentDetails,statistics",
                  id = x) |>
    req_perform() |>
    resp_body_json() -> x
  x[["items"]][[1]][["statistics"]][["viewCount"]]
}
```



```{r}
#using that function to make a list of the view counts of top 50 youtuber
the_list <- list()
for (x in vector) {
  view_count(x) -> y
  the_list[x] <- y
}

view_count_list <- as.data.frame(the_list)

view_count_list |>
  pivot_longer(cols = 1:5,
               names_to = "a",
               values_to = "view_count") |>
  select(view_count) -> view_count_list
```



```{r}
#getting the list of subscriber count
base_url <- "https://www.googleapis.com/youtube/v3/channels"

sub_count <- function(x) {
  request(base_url) |>
    req_url_query(key = "AIzaSyCq_fI_CnAymFiyFHafXUBGSIVOzwXLGqc",
                  part = "snippet,contentDetails,statistics",
                  id = x) |>
    req_perform() |>
    resp_body_json() -> x
  x[["items"]][[1]][["statistics"]][["subscriberCount"]]
}

the_list <- list()
for (x in vector) {
  sub_count(x) -> y
  the_list[x] <- y
}

sub_count_list <- as.data.frame(the_list)

sub_count_list |>
  pivot_longer(cols = 1:5,
               names_to = "a",
               values_to = "sub_count") |>
  select(sub_count) -> sub_count_list

```



```{r}
#title
base_url <- "https://www.googleapis.com/youtube/v3/channels"

title <- function(x) {
  request(base_url) |>
    req_url_query(key = "AIzaSyCq_fI_CnAymFiyFHafXUBGSIVOzwXLGqc",
                  part = "snippet,contentDetails,statistics",
                  id = x) |>
    req_perform() |>
    resp_body_json() -> x
  x[["items"]][[1]][["snippet"]][["title"]]
}

the_list <- list()
for (x in vector) {
  title(x) -> y
  the_list[x] <- y
}

title_list <- as.data.frame(the_list)

title_list |>
  pivot_longer(cols = 1:5,
               names_to = "a",
               values_to = "title") |>
  select(title) -> title_list
```



```{r}
#country 
base_url <- "https://www.googleapis.com/youtube/v3/channels"

country <- function(x) {
  request(base_url) |>
    req_url_query(key = "AIzaSyCq_fI_CnAymFiyFHafXUBGSIVOzwXLGqc",
                  part = "snippet,contentDetails,statistics",
                  id = x) |>
    req_perform() |>
    resp_body_json() -> x
  x[["items"]][[1]][["snippet"]][["country"]]
}

the_list <- list()
for (x in vector) {
  country(x) -> y
  the_list[x] <- y
}

country_list <- as.data.frame(the_list)

country_list |>
  pivot_longer(cols = 1:5,
               names_to = "a",
               values_to = "country") |>
  select(country) -> country_list
```



```{r}
#video count 
base_url <- "https://www.googleapis.com/youtube/v3/channels"

video_count <- function(x) {
  request(base_url) |>
    req_url_query(key = "AIzaSyCq_fI_CnAymFiyFHafXUBGSIVOzwXLGqc",
                  part = "snippet,contentDetails,statistics",
                  id = x) |>
    req_perform() |>
    resp_body_json() -> x
  x[["items"]][[1]][["statistics"]][["videoCount"]]
}

the_list <- list()
for (x in vector) {
  video_count(x) -> y
  the_list[x] <- y
}

video_count_list <- as.data.frame(the_list)

video_count_list |>
  pivot_longer(cols = 1:5,
               names_to = "a",
               values_to = "video") |>
  select(video) -> video_count_list
```



```{r}
total <- cbind(title_list,country_list, view_count_list, sub_count_list, video_count_list)
```





